### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by smatthews1999** [ehzhang/sense-js#3]
Hi!

Great library!  Thanks.

I am attempting to make a game starting with your "orientation" example.  I have one particular issue that has got me stumped.

In my game the user rolls the ball (as in your demo) but then falls in a hole and must start over.  When the user starts over, the ball should start as if just placed motionless.  

What is happening is that the ball already has some velocity and begins moving immediately in a direction.  The movement is obviously being carried over from the previous state.  I have tried reset as many variables that appear to affect the ball as are available.  i.e. velx, vely=0, reset oldTime, etc.  I imagine that the issue is that behind the scenes the "deviceorientation" event is still in place and is updating the state even when I am trying to reset the environment.

Would it be possible to add a "reset" or "restart" to the Orientation functionality so that the ball would truly reset its movement as it does when first started.

Thanks
Sam

**Comment by ehzhang** [comment]
Depending on how you are implementing your ball, then changes to the library itself would not actually be helpful. Please note that the ball orientation demo is just a demo! The code there is not inherent of the library itself.

Noting that, adding a 'reset' or 'restart' to the Orientation would not actually keep consistent with the way the library works, as the orientation callback currently is meant to fire with any changes that move above the configured thresholds. The library itself is not updating any state for any ball, it is only firing with data.

I can, however, see about adding a 'start' and 'stop' functionality to start and stop things from sensing.
